### ISSUE TITLE
Page-2-structure

### ISSUE THREAD

**Issue by MahmoudJD95** [GSG-FC03/To-do-Team-5#8]
- [ ] Creat HTML Structure
- Creat Add Task Button.
- Add title Start Your First Task.
- [ ] Create Css structure.
-  Make one color background and font family "Amatic SC".
- Make style for area that Task will be in .
- Make style for button.

**Comment by sara219** [comment]
@MahmoudJD95  
write descriptively describe for the page structure (many sections? what it contains, what colour you will use ...etc)
